title: Cameron's 6.1040 Portfolio

markdown: kramdown
highlighter: rouge

github: https://github.com/camtheman256/61040/tree/main

date_format: "%A, %B %e, %Y"

kramdown:
  toc_levels: 1..3

plugins:
  - jekyll-sitemap